#!/bin/bash

# Script to analyze insert size for four sequencing samples
# Author: Generated by Lingma
# Date: 2026-05-18

set -e  # Exit on error

# Define sample directories
SAMPLE_DIRS=(
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_20"
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_21" 
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_72"
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_73"
)

# Output directory
OUTPUT_DIR="/home/gao/projects/2026_Item14_insert_size"
mkdir -p "$OUTPUT_DIR/results"

# Reference genome path (user needs to specify this)
# REF_GENOME="/path/to/reference/genome.fa"
# For now, we'll create a placeholder and user should update this

echo "Please specify the reference genome path in this script before running."
echo "Set REF_GENOME variable to your reference genome FASTA file path."
echo "Example: REF_GENOME=\"/path/to/hg38.fa\""
echo ""
echo "This script requires: bwa, samtools, picard tools"
echo ""

# Uncomment and set your reference genome path below:
# REF_GENOME=""

if [ -z "$REF_GENOME" ] || [ ! -f "$REF_GENOME" ]; then
    echo "ERROR: Reference genome not set or not found!"
    echo "Please edit this script and set REF_GENOME variable."
    exit 1
fi

# Function to get sample name from directory path
get_sample_name() {
    local dir="$1"
    basename "$dir"
}

# Function to find fastq files in directory
find_fastq_files() {
    local dir="$1"
    local r1_files=()
    local r2_files=()
    
    # Look for common fastq patterns
    for file in "$dir"/*_1.fq.gz "$dir"/*_R1_*.fq.gz "$dir"/*_1.fastq.gz; do
        if [ -f "$file" ]; then
            r1_files+=("$file")
        fi
    done
    
    for file in "$dir"/*_2.fq.gz "$dir"/*_R2_*.fq.gz "$dir"/*_2.fastq.gz; do
        if [ -f "$file" ]; then
            r2_files+=("$file")
        fi
    done
    
    if [ ${#r1_files[@]} -eq 0 ] || [ ${#r2_files[@]} -eq 0 ]; then
        echo "ERROR: Could not find paired-end fastq files in $dir"
        return 1
    fi
    
    echo "${r1_files[0]} ${r2_files[0]}"
}

# Main analysis loop
for sample_dir in "${SAMPLE_DIRS[@]}"; do
    if [ ! -d "$sample_dir" ]; then
        echo "WARNING: Sample directory not found: $sample_dir"
        continue
    fi
    
    sample_name=$(get_sample_name "$sample_dir")
    echo "Processing sample: $sample_name"
    
    # Create sample-specific output directory
    sample_output="$OUTPUT_DIR/results/$sample_name"
    mkdir -p "$sample_output"
    
    # Find fastq files
    read r1_file r2_file <<< $(find_fastq_files "$sample_dir")
    if [ $? -ne 0 ]; then
        echo "Skipping sample $sample_name due to missing fastq files"
        continue
    fi
    
    echo "  R1: $r1_file"
    echo "  R2: $r2_file"
    
    # Step 1: Align with BWA (create index if needed)
    if [ ! -f "${REF_GENOME}.bwt" ]; then
        echo "  Creating BWA index for reference genome..."
        bwa index "$REF_GENOME"
    fi
    
    echo "  Aligning reads with BWA..."
    bwa mem -t 4 "$REF_GENOME" "$r1_file" "$r2_file" | samtools view -@ 4 -bS - > "$sample_output/${sample_name}.bam"
    
    # Step 2: Sort BAM file
    echo "  Sorting BAM file..."
    samtools sort -@ 4 -o "$sample_output/${sample_name}.sorted.bam" "$sample_output/${sample_name}.bam"
    
    # Step 3: Index sorted BAM
    echo "  Indexing sorted BAM..."
    samtools index "$sample_output/${sample_name}.sorted.bam"
    
    # Step 4: Calculate insert size metrics using Picard
    echo "  Calculating insert size metrics..."
    picard CollectInsertSizeMetrics \
        I="$sample_output/${sample_name}.sorted.bam" \
        O="$sample_output/${sample_name}_insert_size_metrics.txt" \
        H="$sample_output/${sample_name}_insert_size_histogram.pdf" \
        M=0.05
    
    # Step 5: Extract key statistics
    echo "  Extracting summary statistics..."
    {
        echo "Sample: $sample_name"
        echo "Reference: $REF_GENOME"
        echo "Fastq files: $r1_file, $r2_file"
        echo "=== Insert Size Metrics ==="
        grep -A 20 "MEDIAN_INSERT_SIZE" "$sample_output/${sample_name}_insert_size_metrics.txt" | head -10
        echo ""
    } >> "$OUTPUT_DIR/results/summary.txt"
    
    # Clean up intermediate files (keep sorted BAM and metrics)
    rm "$sample_output/${sample_name}.bam"
    
    echo "  Completed processing $sample_name"
    echo ""
done

echo "Analysis completed!"
echo "Results are in: $OUTPUT_DIR/results/"
echo "Summary: $OUTPUT_DIR/results/summary.txt"