#!/usr/bin/env python3
"""
Insert Size Analysis Script for Four Sequencing Samples

This script analyzes insert size for the following samples:
- YCL_20
- YCL_21  
- YCL_72
- YCL_73

The analysis requires:
1. Reference genome (user needs to specify path)
2. Samtools for BAM processing
3. Picard Tools for insert size metrics (optional)

Author: Generated by Lingma
Date: 2026-05-18
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path


def check_dependencies():
    """Check if required tools are available."""
    tools = ['samtools', 'bwa']
    missing_tools = []
    
    for tool in tools:
        try:
            subprocess.run([tool, '--version'], 
                         capture_output=True, check=True)
        except (subprocess.CalledProcessError, FileNotFoundError):
            missing_tools.append(tool)
    
    if missing_tools:
        print(f"Error: Missing required tools: {', '.join(missing_tools)}")
        print("Please install the missing tools and try again.")
        sys.exit(1)


def get_fastq_files(sample_dirs):
    """Get paired-end FASTQ files from sample directories."""
    fastq_pairs = {}
    
    for sample_dir in sample_dirs:
        sample_name = os.path.basename(os.path.normpath(sample_dir))
        fastq_files = list(Path(sample_dir).glob("*_1.fq.gz"))
        
        if not fastq_files:
            print(f"Warning: No R1 files found in {sample_dir}")
            continue
            
        r1_file = fastq_files[0]
        r2_file = str(r1_file).replace("_1.fq.gz", "_2.fq.gz")
        
        if not os.path.exists(r2_file):
            print(f"Warning: R2 file not found for {r1_file}")
            continue
            
        fastq_pairs[sample_name] = (str(r1_file), r2_file)
        print(f"Found files for {sample_name}:")
        print(f"  R1: {r1_file}")
        print(f"  R2: {r2_file}")
    
    return fastq_pairs


def run_bwa_mem(reference_genome, r1_file, r2_file, output_bam, threads=4):
    """Run BWA-MEM alignment."""
    cmd = [
        'bwa', 'mem',
        '-t', str(threads),
        '-R', f'@RG\\tID:{os.path.basename(r1_file)}\\tSM:{os.path.basename(r1_file)}\\tPL:ILLUMINA',
        reference_genome,
        r1_file,
        r2_file
    ]
    
    # Pipe to samtools for sorting
    with open(output_bam, 'w') as bam_out:
        bwa_process = subprocess.Popen(cmd, stdout=subprocess.PIPE)
        samtools_process = subprocess.Popen(
            ['samtools', 'sort', '-@', str(threads), '-o', output_bam, '-'],
            stdin=bwa_process.stdout,
            stdout=bam_out
        )
        bwa_process.stdout.close()
        samtools_process.wait()
    
    if samtools_process.returncode != 0:
        raise RuntimeError(f"BWA-MEM alignment failed for {r1_file}")


def calculate_insert_size_stats(bam_file):
    """Calculate basic insert size statistics using samtools."""
    cmd = ['samtools', 'stats', bam_file]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    
    insert_sizes = []
    for line in result.stdout.split('\n'):
        if line.startswith('IS'):
            parts = line.split('\t')
            if len(parts) >= 3:
                insert_size = int(parts[1])
                count = int(parts[2])
                insert_sizes.extend([insert_size] * count)
    
    if not insert_sizes:
        return None
    
    # Calculate basic statistics
    mean_insert = sum(insert_sizes) / len(insert_sizes)
    median_insert = sorted(insert_sizes)[len(insert_sizes) // 2]
    
    return {
        'mean': mean_insert,
        'median': median_insert,
        'min': min(insert_sizes),
        'max': max(insert_sizes),
        'total_reads': len(insert_sizes)
    }


def main():
    parser = argparse.ArgumentParser(description='Analyze insert size for sequencing samples')
    parser.add_argument('--reference', required=True, 
                       help='Path to reference genome FASTA file')
    parser.add_argument('--output-dir', default='/home/gao/projects/2026_Item14_insert_size/results',
                       help='Output directory for results')
    parser.add_argument('--threads', type=int, default=4,
                       help='Number of threads to use')
    
    args = parser.parse_args()
    
    # Check dependencies
    check_dependencies()
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Define sample directories
    sample_dirs = [
        '/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_20',
        '/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_21',
        '/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_72',
        '/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_73'
    ]
    
    # Get FASTQ files
    fastq_pairs = get_fastq_files(sample_dirs)
    
    if not fastq_pairs:
        print("Error: No valid FASTQ pairs found!")
        sys.exit(1)
    
    # Process each sample
    results = {}
    for sample_name, (r1_file, r2_file) in fastq_pairs.items():
        print(f"\nProcessing sample: {sample_name}")
        
        bam_file = os.path.join(args.output_dir, f"{sample_name}.sorted.bam")
        stats_file = os.path.join(args.output_dir, f"{sample_name}_insert_stats.txt")
        
        try:
            # Align reads if BAM doesn't exist
            if not os.path.exists(bam_file):
                print(f"  Aligning reads...")
                run_bwa_mem(args.reference, r1_file, r2_file, bam_file, args.threads)
            
            # Index BAM file
            subprocess.run(['samtools', 'index', bam_file], check=True)
            
            # Calculate insert size statistics
            print(f"  Calculating insert size statistics...")
            stats = calculate_insert_size_stats(bam_file)
            
            if stats:
                results[sample_name] = stats
                # Write statistics to file
                with open(stats_file, 'w') as f:
                    f.write(f"Sample: {sample_name}\n")
                    f.write(f"Total paired reads: {stats['total_reads']}\n")
                    f.write(f"Mean insert size: {stats['mean']:.2f}\n")
                    f.write(f"Median insert size: {stats['median']}\n")
                    f.write(f"Min insert size: {stats['min']}\n")
                    f.write(f"Max insert size: {stats['max']}\n")
                
                print(f"  Results saved to: {stats_file}")
            else:
                print(f"  Warning: No insert size data found for {sample_name}")
                
        except Exception as e:
            print(f"  Error processing {sample_name}: {e}")
            continue
    
    # Print summary
    if results:
        print("\n" + "="*60)
        print("INSERT SIZE ANALYSIS SUMMARY")
        print("="*60)
        print(f"{'Sample':<15} {'Mean':<10} {'Median':<10} {'Min':<8} {'Max':<8} {'Reads'}")
        print("-"*60)
        for sample, stats in results.items():
            print(f"{sample:<15} {stats['mean']:<10.2f} {stats['median']:<10} "
                  f"{stats['min']:<8} {stats['max']:<8} {stats['total_reads']}")
        print("="*60)
    else:
        print("No results generated!")


if __name__ == "__main__":
    main()