#!/bin/bash

# Fastp Overlap-based Insert Size Analysis for Four Samples
# This script uses fastp's overlap detection to estimate insert sizes
# without requiring reference genome alignment
#
# Author: Generated by Lingma
# Date: 2026-05-18

set -e

# Activate the regular_bioinfo environment
echo "Activating regular_bioinfo environment..."
source $(conda info --base)/etc/profile.d/conda.sh
conda activate regular_bioinfo

# Verify fastp is available
if ! command -v fastp &> /dev/null; then
    echo "Error: fastp not found in PATH"
    echo "Please ensure you are in the regular_bioinfo environment"
    exit 1
fi

# Define sample directories and output
SAMPLE_DIRS=(
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_20"
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_21"
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_72"
    "/home/gao/Dropbox/Quote_260203003/Raw_Data/YCL_73"
)

OUTPUT_DIR="/home/gao/projects/2026_Item14_insert_size/results_fastp"
mkdir -p "$OUTPUT_DIR"

# Function to process a single sample
process_sample() {
    local sample_dir="$1"
    local sample_name=$(basename "$sample_dir")
    local output_dir="$OUTPUT_DIR/$sample_name"
    mkdir -p "$output_dir"
    
    echo "Processing sample: $sample_name"
    
    # Find FASTQ files
    local r1_files=("$sample_dir"/*_1.fq.gz)
    local r2_files=("$sample_dir"/*_2.fq.gz)
    
    if [ ! -f "${r1_files[0]}" ] || [ ! -f "${r2_files[0]}" ]; then
        echo "  ERROR: Paired-end FASTQ files not found for $sample_name"
        return 1
    fi
    
    local r1="${r1_files[0]}"
    local r2="${r2_files[0]}"
    
    echo "  R1: $(basename "$r1")"
    echo "  R2: $(basename "$r2")"
    
    # Run fastp with comprehensive overlap analysis
    # Key parameters for overlap analysis:
    # --overlap_len_require 20: minimum overlap length to detect
    # --overlap_diff_percent_limit 10: max 10% mismatch in overlap
    # --correction: enable base correction in overlapped regions
    # --merge: merge overlapping reads
    # --json and --html: generate detailed reports
    
    echo "  Running fastp overlap analysis..."
    fastp \
        -i "$r1" \
        -I "$r2" \
        -o "$output_dir/${sample_name}_R1_merged.fq.gz" \
        -O "$output_dir/${sample_name}_R2_unmerged.fq.gz" \
        --merged_out "$output_dir/${sample_name}_merged.fq.gz" \
        --json "$output_dir/${sample_name}_fastp.json" \
        --html "$output_dir/${sample_name}_fastp.html" \
        --report_title "Fastp Insert Size Analysis - $sample_name" \
        --overlap_len_require 20 \
        --overlap_diff_percent_limit 10 \
        --correction \
        --merge \
        --thread 4 \
        --verbose
    
    echo "  Analysis completed for $sample_name"
    echo ""
}

# Process all samples
echo "Starting Fastp Overlap-based Insert Size Analysis"
echo "=================================================="
echo ""

for sample_dir in "${SAMPLE_DIRS[@]}"; do
    if [ -d "$sample_dir" ]; then
        process_sample "$sample_dir"
    else
        echo "WARNING: Directory not found: $sample_dir"
    fi
done

# Generate summary report
echo "Generating summary report..."
generate_summary() {
    echo "Fastp Insert Size Analysis Summary" > "$OUTPUT_DIR/summary.txt"
    echo "==================================" >> "$OUTPUT_DIR/summary.txt"
    echo "" >> "$OUTPUT_DIR/summary.txt"
    
    for sample_dir in "${SAMPLE_DIRS[@]}"; do
        sample_name=$(basename "$sample_dir")
        json_file="$OUTPUT_DIR/$sample_name/${sample_name}_fastp.json"
        
        if [ -f "$json_file" ]; then
            echo "Sample: $sample_name" >> "$OUTPUT_DIR/summary.txt"
            
            # Extract key metrics using jq
            total_reads=$(jq -r '.summary.before_filtering.total_reads // 0' "$json_file")
            merged_reads=$(jq -r '.merge.merged_reads // 0' "$json_file")
            merge_rate=$(jq -r '.merge.merge_rate // 0' "$json_file")
            
            echo "  Total reads: $((total_reads / 2))" >> "$OUTPUT_DIR/summary.txt"
            echo "  Merged reads: $merged_reads" >> "$OUTPUT_DIR/summary.txt"
            echo "  Merge rate: $(printf "%.2f%%" $(echo "$merge_rate * 100" | bc -l))" >> "$OUTPUT_DIR/summary.txt"
            
            # Estimate insert size from read lengths
            r1_len=$(jq -r '.summary.before_filtering.read1_mean_length // 0' "$json_file")
            r2_len=$(jq -r '.summary.before_filtering.read2_mean_length // 0' "$json_file")
            
            if [ "$merged_reads" -gt 0 ]; then
                # For merged reads, insert size ≈ read1_len + read2_len - overlap_len
                avg_overlap=$(jq -r '.merge.average_merged_length // 0' "$json_file")
                if [ "$avg_overlap" -gt 0 ]; then
                    estimated_insert=$((r1_len + r2_len - avg_overlap))
                    echo "  Estimated insert size (merged): ~$estimated_insert bp" >> "$OUTPUT_DIR/summary.txt"
                fi
            else
                min_insert=$((r1_len + r2_len))
                echo "  No merged reads detected" >> "$OUTPUT_DIR/summary.txt"
                echo "  Minimum insert size: > $min_insert bp" >> "$OUTPUT_DIR/summary.txt"
            fi
            
            echo "" >> "$OUTPUT_DIR/summary.txt"
        else
            echo "  WARNING: JSON report not found for $sample_name" >> "$OUTPUT_DIR/summary.txt"
            echo "" >> "$OUTPUT_DIR/summary.txt"
        fi
    done
    
    echo "Summary report generated: $OUTPUT_DIR/summary.txt"
}

# Check if jq is available for JSON parsing
if command -v jq &> /dev/null; then
    generate_summary
else
    echo "Warning: jq not available, skipping detailed summary generation"
    echo "Install jq to get detailed JSON parsing: conda install -c conda-forge jq"
fi

echo ""
echo "Analysis completed!"
echo "Results directory: $OUTPUT_DIR/"
echo ""
echo "Key files for each sample:"
echo "  - ${sample_name}_fastp.json: Detailed JSON report with overlap statistics"
echo "  - ${sample_name}_fastp.html: Interactive HTML report"
echo "  - ${sample_name}_merged.fq.gz: Merged overlapping reads"
echo "  - summary.txt: Overall summary of results"
echo ""
echo "Note: Fastp overlap analysis provides accurate insert size estimates"
echo "only when the insert size is smaller than the combined read length."
echo "For larger insert sizes, it provides a lower bound estimate."