#!/usr/bin/env python3
"""
Check for Primer Dimer Contamination in Sequencing Data

This script analyzes merged reads to detect primer dimer contamination
by examining sequence composition and adapter content.

Author: Generated by Lingma
Date: 2026-05-18
"""

import gzip
import sys
import argparse
from collections import Counter


def check_sequence_composition(fastq_file, sample_name, num_reads=1000):
    """Check sequence composition of merged reads."""
    print(f"Analyzing {sample_name} for primer dimer signatures...")
    
    sequences = []
    try:
        with gzip.open(fastq_file, 'rt') as f:
            count = 0
            while count < num_reads:
                header = f.readline()
                if not header:
                    break
                seq = f.readline().strip()
                f.readline()  # plus line
                f.readline()  # quality line
                
                if seq:
                    sequences.append(seq)
                    count += 1
    except Exception as e:
        print(f"Error reading {fastq_file}: {e}")
        return None
    
    if not sequences:
        print(f"No sequences found in {fastq_file}")
        return None
    
    # Analyze sequence characteristics
    results = {}
    
    # 1. Length distribution
    lengths = [len(seq) for seq in sequences]
    results['mean_length'] = sum(lengths) / len(lengths)
    results['length_range'] = (min(lengths), max(lengths))
    
    # 2. GC content
    gc_contents = []
    for seq in sequences:
        gc_count = seq.count('G') + seq.count('C')
        gc_contents.append(gc_count / len(seq) if len(seq) > 0 else 0)
    results['mean_gc'] = sum(gc_contents) / len(gc_contents)
    
    # 3. Check for common Illumina adapter sequences
    illumina_adapters = [
        "AGATCGGAAGAGC",  # Standard Illumina adapter
        "CTGTCTCTTATA",   # Another common adapter
        "AATGATACGGCGA",  # P5 adapter
        "CAAGCAGAAGACG"   # P7 adapter
    ]
    
    adapter_hits = 0
    for seq in sequences[:100]:  # Check first 100 sequences
        for adapter in illumina_adapters:
            if adapter in seq or adapter in seq[:20] or adapter in seq[-20:]:
                adapter_hits += 1
                break
    
    results['adapter_hit_rate'] = adapter_hits / min(100, len(sequences))
    
    # 4. Sequence complexity (low complexity suggests primer dimers)
    low_complexity_count = 0
    for seq in sequences[:100]:
        unique_bases = len(set(seq))
        if unique_bases < 4:  # Very low complexity
            low_complexity_count += 1
    
    results['low_complexity_rate'] = low_complexity_count / min(100, len(sequences))
    
    return results


def main():
    parser = argparse.ArgumentParser(description='Check for primer dimer contamination')
    parser.add_argument('--results-dir', required=True,
                       help='Directory containing fastp results')
    
    args = parser.parse_args()
    
    samples = ['YCL_20', 'YCL_21', 'YCL_72', 'YCL_73']
    
    print("PRIMER DIMER CONTAMINATION ANALYSIS")
    print("=" * 50)
    print("")
    
    all_results = {}
    for sample in samples:
        merged_file = f"{args.results_dir}/{sample}/{sample}_merged.fq.gz"
        results = check_sequence_composition(merged_file, sample)
        if results:
            all_results[sample] = results
    
    # Print summary
    if all_results:
        print(f"{'Sample':<15} {'Mean Len':<10} {'GC%':<8} {'Adapter%':<12} {'LowComplex%'}")
        print("-" * 70)
        for sample, results in all_results.items():
            mean_len = results['mean_length']
            gc_pct = results['mean_gc'] * 100
            adapter_pct = results['adapter_hit_rate'] * 100
            low_complex_pct = results['low_complexity_rate'] * 100
            
            print(f"{sample:<15} {mean_len:<10.1f} {gc_pct:<8.1f} {adapter_pct:<12.1f} {low_complex_pct:.1f}")
        
        print("")
        print("INTERPRETATION:")
        print("- High adapter percentage (>50%) suggests primer dimer contamination")
        print("- Low sequence complexity (<4 unique bases) indicates technical artifacts")
        print("- Mean length around 60bp matches primer dimer size range")
        print("")
        print("RECOMMENDATION:")
        print("If adapter percentage is high and mean length is ~60bp,")
        print("this confirms primer dimer contamination. Consider re-preparing libraries.")
    else:
        print("No results generated - check file paths and permissions.")


if __name__ == "__main__":
    main()